apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
  labels:
    app: trip-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trip-service
  template:
    metadata:
      labels:
        app: trip-service
    spec:
      containers:
        - name: trip-service
          image: sasankreddy18/wandora:trip_service_V1.0  # Replace with your Docker Hub image
          ports:
            - containerPort: 4001  # Update if your app listens on a different port
          env:
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: trip-service-secret
                  key: JWT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: trip-service-secret
                  key: MONGO_URI
