apiVersion: v1
kind: Service
metadata:
  name: trip-service
  labels:
    app: trip-service
spec:
  selector:
    app: trip-service
  ports:
    - protocol: TCP
      port: 4001  # Exposed service port
      targetPort: 4001  # Port on the container
  type: ClusterIP
