apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  labels:
    app: user-service
type: Opaque
data:
  JWT_SECRET: NmQ3MjliNmVkN2NhZDI2OWVkZDFiZTAyNDAxMjcxZmI0MjUwMTc1YmFiMjRlZmUyMWZiOWEwZGZlZmIxNzgzMWNkZGY1MGJjM2YyNWY3N2EzZjhiMWU5ZGEzNTQwNzc2MGY5ZjgzZjNhMDNiMGE5MjhjMjY4YzFmZGIxMDAzM2U=  # Base64 encoded
  MONGO_URI: bW9uZ29kYitzcnY6Ly9UTVMtYWRtaW46VE1TLWFkbWluQHRtcy1kZXYubnpwZmoubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPVRNUy1ERVY=
