apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 4000  # Exposed service port
      targetPort: 4000  # Port on the container
  type: ClusterIP
