apiVersion: v1
kind: Service
metadata:
  name: registration-service
  labels:
    app: registration-service
spec:
  selector:
    app: registration-service
  ports:
    - protocol: TCP
      port: 4002  # Exposed service port
      targetPort: 4002  # Port on the container
  type: ClusterIP
