apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  labels:
    app: user-service
type: Opaque
data:
  JWT_SECRET: *********  # Base64 encoded
  MONGO_URI: *********   # Base64 encoded
